name: brainiacz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0 
  firebase_auth: ^4.19.0 
  cloud_firestore: ^4.15.0 
  firebase_storage: ^11.6.0 
  firebase_messaging: ^14.7.0 
  firebase_analytics: ^10.7.0 
  firebase_crashlytics: ^3.2.0 
  firebase_remote_config: ^4.2.0 
  provider: ^6.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.1.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  table_calendar: ^3.0.9
  flutter_time_picker_spinner: ^2.0.0
  intl: ^0.18.1
  test: ^1.25.8
  mockito: ^5.4.5
  url_launcher: ^6.2.5
  rxdart: ^0.27.7
  permission_handler: ^11.0.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/brainiacz logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/